# https://aka.ms/yaml

trigger:
  - master

variables:
    regression: 1

jobs:
  - job: build_ubuntu
    displayName: Ubuntu
    pool:
      vmImage: 'Ubuntu-22.04'
    timeoutInMinutes: 120
    strategy:
      matrix:
        avx2:
          SIMD: 'AVX2'
          STATIC: 1
          MPI: 0
          BUILD_TYPE: Release
        sse41:
          SIMD: 'SSE4_1'
          STATIC: 1
          MPI: 0
          BUILD_TYPE: Release
        sse2:
          SIMD: 'SSE2'
          STATIC: 1
          MPI: 0
          BUILD_TYPE: Release
        avx2_mpi:
          SIMD: 'AVX2'
          STATIC: 0
          MPI: 1
          BUILD_TYPE: Release
        asan:
          SIMD: 'AVX2'
          STATIC: 0
          MPI: 0
          BUILD_TYPE: ASanOpt
    
    steps:
      - checkout: self
        submodules: true
      - script: |
          #sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 libgcc-11-dev build-essential
        retryCountOnTaskFailure: "2"
        displayName: Install newer G++
      - script: |
          sudo apt-get update
          sudo apt-get -y install mpi-default-dev mpi-default-bin
        displayName: Install Dependencies
        retryCountOnTaskFailure: "2"
        condition: eq(variables['MPI'], 1)
      - script: |
          mkdir build && cd build
          export CC=gcc-11 ; export CXX=g++-11
          if [ "${STATIC}" -eq "1" ]; then
            LIBGOMP=/usr/lib/gcc/x86_64-linux-gnu/11
            cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DFORCE_STATIC_DEPS=1 -DHAVE_TESTS=1 \
              -DOpenMP_C_FLAGS="-fopenmp -I${LIBGOMP}" -DOpenMP_C_LIB_NAMES=gomp -DOpenMP_CXX_FLAGS="-fopenmp -I${LIBGOMP}" -DOpenMP_CXX_LIB_NAMES=gomp -DOpenMP_gomp_LIBRARY=${LIBGOMP}/libgomp.a \
              -DENABLE_WERROR=1 -DHAVE_${SIMD}=1 -DHAVE_MPI=${MPI} ..
          else
            cmake -DHAVE_SANITIZER=1 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DHAVE_TESTS=1 \
              -DENABLE_WERROR=1 -DHAVE_${SIMD}=1 -DHAVE_MPI=${MPI} ..
          fi

          make -j $(nproc --all)
        displayName: Build MetaEuk
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}/tests
          ./run.sh "${BUILD_SOURCESDIRECTORY}/build/src/metaeuk"
        displayName: Run Regression Suite
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        condition: eq(variables['STATIC'], 1)
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/src/metaeuk
          artifactName: metaeuk-linux-$(SIMD)

  - job: build_ubuntu_cross
    displayName: Ubuntu Cross-Compile
    pool:
      vmImage: 'Ubuntu-22.04'
    timeoutInMinutes: 120
    strategy:
      matrix:
        #power8:
        #  SIMD: POWER8
        #  ARCH: ppc64el
        #  CPREF: powerpc64le
        power9:
          SIMD: POWER9
          ARCH: ppc64el
          CPREF: powerpc64le
        arm64:
          SIMD: ARM8
          ARCH: arm64
          CPREF: aarch64

    steps:
      - script: |
          CODENAME=$(lsb_release -cs)
          sudo dpkg --add-architecture "$ARCH"
          cat << HEREDOC | sudo tee /etc/apt/sources.list
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${CODENAME} main universe multiverse
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates main universe multiverse
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${CODENAME}-backports main universe multiverse
          deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ ${CODENAME}-security main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME} main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME}-updates main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME}-backports main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME}-security main universe multiverse
          HEREDOC
          sudo apt-get update
          sudo apt-get -y install -o APT::Immediate-Configure=false crossbuild-essential-$ARCH zlib1g-dev:$ARCH libbz2-dev:$ARCH
        retryCountOnTaskFailure: "2"
        displayName: Install Toolchain
      - script: |
          mkdir build && cd build
          LIBGOMP=/usr/lib/gcc-cross/${CPREF}-linux-gnu/11;
          CC=${CPREF}-linux-gnu-gcc CXX=${CPREF}-linux-gnu-g++ \
           cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DHAVE_TESTS=1 -DFORCE_STATIC_DEPS=1 \
            -DOpenMP_C_FLAGS="-fopenmp -I${LIBGOMP}" -DOpenMP_C_LIB_NAMES=gomp -DOpenMP_CXX_FLAGS="-fopenmp -I${LIBGOMP}" -DOpenMP_CXX_LIB_NAMES=gomp -DOpenMP_gomp_LIBRARY=${LIBGOMP}/libgomp.a \
            -DENABLE_WERROR=1 -DHAVE_${SIMD}=1 ..
          make -j $(nproc --all)
        displayName: Build MetaEuk
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/src/metaeuk
          artifactName: metaeuk-linux-$(SIMD)

  - job: build_macos
    displayName: macOS
    pool:
      vmImage: 'macos-latest'
    steps:
      - checkout: self
        submodules: true
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}
          ./lib/mmseqs/util/build_osx.sh . build metaeuk
        displayName: Build MetaEuk
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}/tests
          ./run.sh "${BUILD_SOURCESDIRECTORY}/build/metaeuk"
        displayName: Run Regression Suite
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/metaeuk
          artifactName: metaeuk-darwin-universal

  - job: upload_artifacts
    displayName: Upload Artifacts
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn:
      - build_macos
      - build_ubuntu
      - build_ubuntu_cross
    steps:
      - script: |
          cd "${BUILD_SOURCESDIRECTORY}"
          mkdir metaeuk
          cp -f README.md LICENCE.md metaeuk
          mkdir metaeuk/bin
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metaeuk-darwin-universal
          targetPath: $(Build.SourcesDirectory)/metaeuk/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metaeuk/bin/metaeuk"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metaeuk
          archiveFile: $(Build.SourcesDirectory)/metaeuk-osx-universal.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metaeuk-linux-SSE2
          targetPath: $(Build.SourcesDirectory)/metaeuk/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metaeuk/bin/metaeuk"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metaeuk
          archiveFile: $(Build.SourcesDirectory)/metaeuk-linux-sse2.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metaeuk-linux-SSE4_1
          targetPath: $(Build.SourcesDirectory)/metaeuk/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metaeuk/bin/metaeuk"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metaeuk
          archiveFile: $(Build.SourcesDirectory)/metaeuk-linux-sse41.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metaeuk-linux-AVX2
          targetPath: $(Build.SourcesDirectory)/metaeuk/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metaeuk/bin/metaeuk"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metaeuk
          archiveFile: $(Build.SourcesDirectory)/metaeuk-linux-avx2.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metaeuk-linux-ARM8
          targetPath: $(Build.SourcesDirectory)/metaeuk/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metaeuk/bin/metaeuk"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metaeuk
          archiveFile: $(Build.SourcesDirectory)/metaeuk-linux-arm64.tar.gz
          includeRootFolder: true
          archiveType: tar
      # - task: DownloadPipelineArtifact@1
      #   inputs:
      #     artifactName: metaeuk-linux-POWER8
      #     targetPath: $(Build.SourcesDirectory)/metaeuk/bin
      # - script:
      #     chmod +x "${BUILD_SOURCESDIRECTORY}/metaeuk/bin/metaeuk"
      # - task: ArchiveFiles@2
      #   inputs:
      #     rootFolderOrFile: $(Build.SourcesDirectory)/metaeuk
      #     archiveFile: $(Build.SourcesDirectory)/metaeuk-linux-ppc64le-power8.tar.gz
      #     includeRootFolder: true
      #     archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metaeuk-linux-POWER9
          targetPath: $(Build.SourcesDirectory)/metaeuk/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metaeuk/bin/metaeuk"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metaeuk
          archiveFile: $(Build.SourcesDirectory)/metaeuk-linux-ppc64le-power9.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadSecureFile@1
        inputs:
          secureFile: azure_upload_metaeuk
        displayName: Get Deployment Key
      - script: |
          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
          ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
          cd "${BUILD_SOURCESDIRECTORY}"
          ssh-keygen -Y sign -f ~/.ssh/id_rsa -n file \
            metaeuk-osx-universal.tar.gz \
            metaeuk-linux-sse2.tar.gz \
            metaeuk-linux-sse41.tar.gz \
            metaeuk-linux-avx2.tar.gz \
            metaeuk-linux-arm64.tar.gz \
            metaeuk-linux-ppc64le-power9.tar.gz
          curl --retry 5 --retry-all-errors -X POST \
            -F file[]=@metaeuk-osx-universal.tar.gz -F signature[]=@metaeuk-osx-universal.tar.gz.sig \
            -F file[]=@metaeuk-linux-sse2.tar.gz -F signature[]=@metaeuk-linux-sse2.tar.gz.sig \
            -F file[]=@metaeuk-linux-sse41.tar.gz -F signature[]=@metaeuk-linux-sse41.tar.gz.sig \
            -F file[]=@metaeuk-linux-avx2.tar.gz -F signature[]=@metaeuk-linux-avx2.tar.gz.sig \
            -F file[]=@metaeuk-linux-arm64.tar.gz -F signature[]=@metaeuk-linux-arm64.tar.gz.sig \
            -F file[]=@metaeuk-linux-ppc64le-power9.tar.gz -F signature[]=@metaeuk-linux-ppc64le-power9.tar.gz.sig \
            -F identifier="metaeuk" -F directory="${BUILD_SOURCEVERSION}" \
              https://mmseqs.com/upload
